#!/bin/sh
#
# A tool to administer OCF resources directly.
#
# http://github.com/joekhoobyar/ha-tools
#
# Author:		Joe Khoobyar <joe@ankhcraft.com>
# License:	GNU General Public License (GPL) version 2
# Copyright (c) 2009 All Rights Reserved
#

version=0.1
progname=$(basename $0)

print_usage() {
    cat <<EOF
Usage: $progname resource-agent [options] command [resource-id]

A tool to deal with errors in the CIB.

Resource Agent:

  A fully-qualified resource agent name, such as: heartbeat/IPaddr2

Options:
  -h, --help          print this usage message
  -V, --version       print program version
  -v, --verbose       verbose output
  -p, --param         OCF parameters, in the form:  name="value"

Commands:

  -M, --metadata      display the resource agent's metadata
  -C, --validate-all  validate the resource and it's configuration
  -m, --monitor       monitor the resource
  -s, --status        check the resource's status, a la an LSB initscript
  -A, --start         stop the resource
  -Z, --stop          start the resource
  -R, --reload        gracefully reload the resource
EOF
}

print_version()
{
    cat <<EOF
$progname (ha-tools) $version
Copyright (C) 2009 All Rights Reserved
Written by Joe Khoobyar <joe@ankhcraft.com>
EOF
}

: ${OCF_ROOT:=/usr/lib/ocf}
OCF_BIN=$OCF_ROOT/resource.d
export OCF_ROOT

# Check the resource agent for validity.  Try to auto-detect when not fully-qualified.
agent="$1"
shift
if [ -z "$agent" ]; then
	print_usage; exit 1
elif [ "$agent" != "${agent##*::}" ]; then
	agent_bin="$OCF_BIN/${agent//:://}"
	if ! [ -x "$agent_bin" ]; then
		echo "$progname: error - no such resource agent: $agent" 1>&2
		print_usage; exit 1;
	fi
elif [ -x "$OCF_BIN/heartbeat/$agent" ]; then
	agent="heartbeat::$agent"
	echo "$progname: warning - guessing fully-qualified resource agent name: $agent" 1>&2
	agent_bin="$OCF_BIN/${agent//:://}"
else
	agent=$(find $OCF_BIN -maxdepth 2 -mindepth 2 -name IPaddr2 -not -type d | sed -ne 's@^/usr/lib/ocf/resource.d/\([^/]\+\)/@\1::@p' | head -1)
	if [ -z "$agent" ]; then
		echo "$progname: error - no such resource agent: $agent" 1>&2
		print_usage; exit 1
	fi
	echo "$progname: warning - guessing fully-qualified resource agent name: $agent" 1>&2
	agent_bin="$OCF_BIN/${agent//:://}"
fi

SHORTOPTS="hVvp:MCmsAZR"
LONGOPTS="help,version,verbose,param,metadata,validate-all,monitor,status,start,stop,reload"
if $(getopt -T >/dev/null 2>&1) ; [ $? = 4 ] ; then # New longopts getopt.
    OPTS=$(getopt -o $SHORTOPTS --long $LONGOPTS -n "$progname" -- "$@")
else
    case $1 in --help) print_usage; exit 0 ;; esac
    case $1 in --version) print_version ; exit 0 ;; esac
    OPTS=$(getopt $SHORTOPTS "$@")
fi 

[ "$OPTS" = " --" ] && OPTS=" -h --"

eval set -- "${OPTS}"

while [ $# -gt 0 ]; do
case $1 in
  -h|--help)
    print_usage; exit 0
    ;;
  -V|--version)
    print_version; exit 0
    ;;
  -v|--verbose)
    export VERBOSE=1
    ;;
  -M|--metadata)
		env $agent_args $agent_bin meta-data
  	;;
  -C|--validate-all)
		env $agent_args OCF_RESOURCE_INSTANCE="$2" $agent_bin validate-all; shift
  	;;
  -m|--monitor)
		env $agent_args OCF_RESOURCE_INSTANCE="$2" $agent_bin monitor; shift
  	;;
  -s|--status)
		env $agent_args OCF_RESOURCE_INSTANCE="$2" $agent_bin status; shift
  	;;
  -A|--start)
		env $agent_args OCF_RESOURCE_INSTANCE="$2" $agent_bin start; shift
  	;;
  -Z|--stop)
		env $agent_args OCF_RESOURCE_INSTANCE="$2" $agent_bin stop; shift
  	;;
  -R|--reload)
		env $agent_args OCF_RESOURCE_INSTANCE="$2" $agent_bin reload; shift
  	;;
  -p|--param)
		agent_args="$agent_args OCF_RESKEY_${2%%=*}=${2#*=} "; shift
  	;;
  --)
    shift
    break
    ;;
  *)
    echo "Internal Error: option processing error: $1" 1>&2
    exit 1
    ;;
esac
shift
done

